---

---

apiVersion: v1
kind: Pod
metadata:
  name: sec-test
  namespace: default
  labels:
    run: busybox
spec:
  securityContext:
    runAsUser: 1553048 # u6040124
    runAsGroup: 1722 # chpc
  containers:
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - name: sec-vol
      mountPath: /sec-demo
  volumes:
  - name: sec-vol
    emptyDir: {}
